
services:
  dev-server:
    build:
      context: .
      dockerfile: Dockerfile
    
    container_name: moo-ma-ka-kai-dev

    ports:
      - "8080:8080"

    volumes:
      - .:/app
      - /app/node_modules

    tty: true

    restart: unless-stopped